DELETE  http://localhost:8080/events/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyaW5nZmlyZWhqYWtlODhAZ21haWwuY29tIiwiZXhwIjoxNzA1OTgwNTE3LCJ1c2VySWQiOjJ9.1ROv1zRLs3FAFzrUg7D7V2M6oHuRJDGQw0kra7RFzTc
